#
# Copyright (c) 2026 The ZMK Contributors
# SPDX-License-Identifier: MIT
#

# Basic ZMK features
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_KEYBOARD_NAME="Verdant02"

# BLE connection limits
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5

# Needed for per-key RGB / WS2812 LED
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=0

# Needed for media/consumer key codes
CONFIG_ZMK_MEDIA=y
